name: Install and deploy k3s and kubectl

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Testing
      run: |
        sudo apt install npm
        sudo npm cache clean -f
        sudo npm install -g n
        sudo n stable
        sudo npm install -g @devcontainers/cli
        devcontainer up --workspace-folder ${PWD}
        sleep 10
        kubectl get pods -A


