name: Install and deploy k3s and kubectl

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Testing
      run: |
        whoami
        echo $PWD
        cut -d: -f1 /etc/passwd
        id -u
        sudo id -u


